# -*- coding: utf-8 -*-
"""silver_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18kzmxCkua-LQBUTGRQ4lEW8YUOiLpvsF

## **Import spark functions and libraries**
"""

from pyspark import *
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *

"""## **Data Reading**"""

df = spark.read.format('parquet')\
             .option('inferschema', 'true')\
             .option('header','true')\
            .load('abfss://bronze@mynewadlsaccount.dfs.core.windows.net/carsales_rawdata')

display(df)

"""**Transformations**"""

df= df.withColumn('Model_category', split(col('Model_ID'), '-')[0])\
             .withColumn('Rev_per_unit', col('Revenue')/col('Units_sold'))

display(df)

"""**Group by and visualizations**"""

display(df.groupBy('Year','Branch_Name').agg(sum('Units_sold').alias('Total_units_sold')).sort('Year','Total_units_sold',ascending=[1,0]))

"""**writing in to the silver container**"""

df.write.format('parquet')\
             .option('header','true')\
             .mode('overwrite')\
            .save('abfss://silver@mynewadlsaccount.dfs.core.windows.net/carsales')

# Commented out IPython magic to ensure Python compatibility.
# %sql
select * from parquet.`abfss://silver@mynewadlsaccount.dfs.core.windows.net/carsales`